### ISSUE TITLE
the official Slowfast and Omnivore features

### ISSUE THREAD

**Issue by wolfworld6** [SichengMo/Ego4D_NLQ_Actionformer#1]
hi, thx, could you share the official Slowfast and Omnivore features? Official data is not available for download in China？

**Comment by SichengMo** [comment]
I think we should not share those features. You can request access for Ego4d Dataset via link [https://ego4d-data.org/#download](https://ego4d-data.org/#download).

**Comment by SichengMo** [comment]
Based on this website (https://ego4d-data.org/docs/), now the full Ego4D dataset is accessible from China without the use of a VPN or proxy server!
