### ISSUE TITLE
Fail to reproduce the results

### ISSUE THREAD

**Issue by Yuxinn-J** [SichengMo/Ego4D_NLQ_Actionformer#2]
Hii, I'm having a bit of trouble reproducing the results you achieved. 
I've followed the instructions in your codebase, but the evaluation results, as shown in the figure below, are noticeably lower compared to yours. 
![image](https://github.com/SichengMo/Ego4D_NLQ_Actionformer/assets/73170270/dac1f207-56af-4220-8f9c-72577ae7e094)
Could you please share some insights on areas where I might need to be extra cautious during the training? Also, will you release the checkpoint for reference? Thanks a bunch!

**Comment by SichengMo** [comment]
Hi, thanks for reaching out. I reproduced the results without any modification to our code.

I have uploaded the checkpoint to https://drive.google.com/file/d/1nBGREUVUM10sQI2cwMgONSDfS3TQYMT1/view 

You can do the evaluation using the checkpoint and compare those training logs. The final score of this checkpoint is 

Rank@1, IoU@0.1: 17.58
Rank@1, IoU@0.3: 9.76
Rank@1, IoU@0.5: 3.69
Rank@1, IoU@0.7: 0.98
Rank@1, IoU@0.9: 0.05

-----

Rank@5, IoU@0.1: 36.91
Rank@5, IoU@0.3: 24.65
Rank@5, IoU@0.5: 11.74
Rank@5, IoU@0.7: 2.92
Rank@5, IoU@0.9: 0.10

**Comment by Yuxinn-J** [comment]
Thanks for sharing the checkpoint! I'll make another attempt to reproduce the results. really appreciate your help.
